networks:
  my_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dietku_app
    container_name: dietku_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: dietku_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - "8090:8080"
    networks:
      - my_network
    restart: always

# for firat time create laravel project
# Uncomment the following section to create a Laravel project on first run

#   engine:
#     build:
#       context: .
#       dockerfile: Dockerfile.engine
#     image: dietku_engine
#     container_name: dietku_engine
#     volumes:
#       - ./:/var/www
#     working_dir: /var/www
#     entrypoint:
#       - /usr/local/bin/entrypoint-engine.sh
#     command: []
#     restart: "no"

volumes:
  db_data:
